"""empty message

Revision ID: 31dac29c31d6
Revises: 5d0ee5539b5e
Create Date: 2023-07-14 02:24:47.448670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31dac29c31d6'
down_revision = '5d0ee5539b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p_flag', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('group01', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('group02', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('group03', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('group04', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('group05', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('group06', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('group07', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('group08', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('group09', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('group10', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('group11', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('group12', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('group13', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('group14', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('group15', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('group16', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('group17', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('group18', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('group19', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('group20', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('group20')
        batch_op.drop_column('group19')
        batch_op.drop_column('group18')
        batch_op.drop_column('group17')
        batch_op.drop_column('group16')
        batch_op.drop_column('group15')
        batch_op.drop_column('group14')
        batch_op.drop_column('group13')
        batch_op.drop_column('group12')
        batch_op.drop_column('group11')
        batch_op.drop_column('group10')
        batch_op.drop_column('group09')
        batch_op.drop_column('group08')
        batch_op.drop_column('group07')
        batch_op.drop_column('group06')
        batch_op.drop_column('group05')
        batch_op.drop_column('group04')
        batch_op.drop_column('group03')
        batch_op.drop_column('group02')
        batch_op.drop_column('group01')
        batch_op.drop_column('p_flag')

    # ### end Alembic commands ###
